spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task-service/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

